import { MoralisProvider } from "react-moralis"
import { NotificationProvider } from "web3uikit"
import "../styles/globals.css"
import Header from "../components/Header"
import Head from 'next/head'

function App({ Component, pageProps }) {
    return (
        <div>
        <Head>
        <title>NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
        <MoralisProvider initializeOnMount={false}>
            <NotificationProvider>
                <Header/>
                <Component {...pageProps} />
            </NotificationProvider>
        </MoralisProvider>
        </div>
    )
}

export default App

